# Generated by Django 2.2.5 on 2020-08-10 20:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fans',
            field=models.ManyToManyField(related_name='idols', to=settings.AUTH_USER_MODEL),
        ),
    ]
